# Action to build the maven application and upload the artifact to Sonatype and deploy using terraform

name: Sonatype Build and Deploy

on:
    workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    NEXUS_URL: ${{ secrets.NEXUS_URL }}
    NEXUS_SNAPSHOTS_REPOSITORY: ${{ secrets.NEXUS_SNAPSHOT_URL }}
    
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'

            - name: Build with Maven
              run: mvn clean install

            - name: Deploy to Sonatype
              env:
                  NEXUS_USERNAME: ${{ secrets.NEXUS_USER }}
                  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
                  NEXUS_URL: ${{ secrets.NEXUS_URL }}
                  NEXUS_SNAPSHOT_URL: ${{ secrets.NEXUS_SNAPSHOT_URL }}
              run: mvn deploy --settings .github/maven/settings.xml

            - name: Terraform init and destroy
              run: |
                  cd terraform
                  terraform init
                  terraform destroy -auto-approve \
                      -var="nexus_pass=${{ secrets.NEXUS_PASSWORD }}"

            - name: Terraform plan
              run: |
                  cd terraform
                  terraform plan

            - name: Terraform apply
              run: 
                  cd terraform
                  terraform apply -auto-approve \
                      -var="nexus_pass=${{ secrets.NEXUS_PASSWORD }}"