# Action to build the maven application and upload the artifact to Sonatype and deploy using terraform

name: Sonatype Build and Deploy

on:
    workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    NEXUS_URL: ${{ secrets.NEXUS_URL }}
    NEXUS_SNAPSHOTS_REPOSITORY: ${{ secrets.NEXUS_SNAPSHOTS_REPOSITORY }}
    
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'

            - name: Download maven settings
              run: curl -u ${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASSWORD }} http://${{ secrets.NEXUS_HOST }}:8081/repository/maven-releases/vprofile/maven-settings/1.0.0/maven-settings-1.0.0.xml -o ~/.m2/settings.xml --create-dirs

            - name: Build with Maven
              run: mvn clean install

            - name: Upload Artifact
              run: mvn deploy -DskipTests=true