# Action to build the maven application and upload the artifact to AWS S3 bucket and deploy using terraform

name: Build and Deploy

on:
    workflow_dispatch:

env:
    VPRO_S3_BUCKET_NAME: ${{ secrets.VPRO_S3_BUCKET_NAME }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'

            - name: Build with Maven
              run: mvn clean install

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            
            - name: Upload the Artifact to S3
              run: aws s3 cp ./target/vprofile-v2.war s3://${{ env.VPRO_S3_BUCKET_NAME }}

            - name: Terraform init and plan inside terraform directory
              run: |
                  cd terraform
                  terraform init
                  terraform plan

            - name: Terraform apply inside terraform directory
              run: |
                  cd terraform
                  terraform apply -auto-approve