# Github Action for running terraform destroy

name: Terraform Destroy

on:
    workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    terraform_destroy:
        name: Terraform Destroy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Terraform init and destroy
              run: |
                  cd terraform
                  terraform init
                  terraform destroy -auto-approve
